### PR TITLE
NP-11911 added leave balance type to the pay element api doc

### PR DESCRIPTION
**Pull request by alvindaiyan**

### CODE REVIEW

**Comment by hariendemel** [comment]
The font size of the items in the list is larger than the rest. Looks like's it's been inherited from general ul and ol elements. There should be a specific style for lists inside attribute tables.

**Comment by hariendemel** [comment]
Just noticed that lslLiable property starts with a capital letter.

**Comment by alvindaiyan** [comment]
@hariendemel  lsLiable is an "L -> l" not "I -> i", fixed the list font size

**Comment by hariendemel** [comment]
Font size is fixed there, but broken everywhere else. I specifically said not to change the font size for all ul elements!

**Pull request merged**
