### PR TITLE
pay elements api

### PR DESCRIPTION
**Pull request by alvindaiyan**
I've added the pay elements docs for start. 
@dianadem  @hariendemel can you check the docs and let me know if there is any problem?

### CODE REVIEW

**Comment by hariendemel** [comment]
- "Returns specified employee's payslip in the specified payroll" - looks like a direct copy and paste.

- How 'pay element' is spelled in descriptions isn't consistent -  Pay element,  Pay Element and pay element. Probably should go with all lower case.

- This seams to be the first time we are using boolean properties - a property or two is prefixed with 'is' but most of them aren't. Not sure how we want to name them (better to get Nimo's opinion on it) but it should be consistent.

- Finishing attribute descriptions with a fullstop or not is not consistent.

- I don't understand this statement. ">If the pay element applies reduce superable, the value will be true." It also starts with a >.

- bSBAccountNumber isn't proper camel case - it should be bsbAccountNumber. In the description, it should be BSB.

- Should address be renamed as doneeAddress?

- Not clear: "If the pay element is employment termination payment no Lumpd"

- Is 'etp' an abbreviation? Then should be in uppercase.

- "Whether the pay element is from system default or organisation" - the sentence is not clear. Also what are the possible values for this String property?

- The name of the custome - misspelled.

**Comment by hariendemel** [comment]
[x] ETP should be explained - Employment Termination Payment

[x] Lumpd (in description) - this should be LumpD

**Comment by hariendemel** [comment]
@duckranger do you want to have a look at this change?

**Comment by duckranger** [comment]
done

**Pull request merged**
