### PR TITLE
add leave requests

### PR DESCRIPTION
**Pull request by hariendemel**

### CODE REVIEW

**Comment by duckranger** [comment]
# I think we need to encode the GET requests properly. we currently show /api/v1/leaves/requests?status=Pending&leaveBalanceType=Annual Leave - but it should be /api/v1/leaves/requests?status=Pending&leaveBalanceType=Annual%20Leave. This happens multiple times. (And need to check if hapens with other resoureces)
# The first GET seems to get all leaves in the org. Is this paged?
# /api/v1/leaves/requests/current and /api/v1/employees/{employeeId}/leaves/requests - the title says request - single but should be plural - requests
# Response examples missing everywhere

**Comment by hariendemel** [comment]
Rather than using the actual parameter values, we should use leaveBalanceType={xxx} and status={yyy} to match the existing URLs

**Comment by dianadem** [comment]
- Added examples
- Corrected request parameters
- Corrected spelling

**Comment by duckranger** [comment]
1. for /api/v1/leaves/requests in the response example the href seems wrong (the quote is in the middle of the uri)

2. Retrieve current leave request - still needs plural.
3. Retrieve current leave request - in the response example - the href is not closed with a quote
4. /api/v1/employees/{employeeId}/leaves/requests same issue as (3)
5. Do we change to use @hariendemel's note about the leave balances {xxx} ?

**Comment by dianadem** [comment]
All 5 points have been addressed

**Pull request merged**
